import streamlit as st
import google.generativeai as genai
import tempfile
import os
import time
import pandas as pd
import io
from fpdf import FPDF

# --- 🌙 DARK/LIGHT & MOBILE LAYOUT ---
st.set_page_config(
    page_title="Gemini PDI Field Assistant",
    layout="wide", 
    initial_sidebar_state="auto", 
    page_icon="🔬"
)

st.markdown("""
    <style>
    .stTable { overflow-x: auto !important; }
    [data-testid="stSidebar"] { min-width: 280px; max-width: 320px; }
    </style>
    """, unsafe_allow_html=True)

# --- 🌟 PERFECT PROPORTION PDF TABLE FUNCTION ---
def create_pdf_table(df):
    # Landscape orientation, A4 format, aur auto-page break set kiya hai
    pdf = FPDF(orientation="L", unit="mm", format="A4") 
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    
    # --- Modern Header Setup ---
    pdf.set_font("Helvetica", 'B', 16) 
    pdf.set_text_color(0, 51, 102) # Dark Blue Color
    pdf.cell(0, 8, txt="HITES PDI Technical Report", align='C', ln=1)
    
    pdf.set_font("Helvetica", size=10)
    pdf.set_text_color(100, 100, 100) # Grey color
    pdf.cell(0, 6, txt="Generated by: Mohammad Sajid (Biomedical Engineer Grade 1)", align='C', ln=1)
    pdf.ln(5) # Header ke baad thodi jagah chodi
    
    # --- Table Styling ---
    pdf.set_text_color(0, 0, 0) # Wapas Black color table data ke liye
    
    # PERFECT WIDTH RATIO: S.No (5%), English (27%), Hindi (28%), Inspection Guide (40%)
    col_widths_ratio = (5, 27, 28, 40)
    
    with pdf.table(
        col_widths=col_widths_ratio,
        text_align=("CENTER", "LEFT", "LEFT", "LEFT"),
        line_height=6, # Line height ko thoda compact kiya taaki zyada text fit ho bina bhid ke
        borders_layout="ALL"
    ) as table:
        
        # Table Header Row
        header_row = table.row()
        pdf.set_font("Helvetica", 'B', 10) # Header thoda bada
        for col in df.columns:
            header_row.cell(str(col))
            
        # Table Data Rows
        pdf.set_font("Helvetica", '', 9) # Data ka font 9 kiya taaki lamba text neat lage
        for _, data_row in df.iterrows():
            row = table.row()
            for item in data_row:
                # Text ko clean kar rahe hain taaki error na aaye
                clean_text = str(item).encode('latin-1', 'replace').decode('latin-1')
                row.cell(clean_text)
                
    return bytes(pdf.output())

# --- SECURE API CONFIGURATION ---
try:
    api_key = st.secrets["GEMINI_API_KEY"]
    genai.configure(api_key=api_key)
except Exception:
    st.error("❌ API Key nahi mili! Settings > Secrets mein GEMINI_API_KEY set karein.")
    st.stop()

# --- Session State ---
if "gemini_file" not in st.session_state: st.session_state.gemini_file = None
if "current_filename" not in st.session_state: st.session_state.current_filename = ""
if "report_df" not in st.session_state: st.session_state.report_df = None
if "chat_history" not in st.session_state: st.session_state.chat_history = []

# --- PROFESSIONAL PDF SIDEBAR 📑 ---
with st.sidebar:
    st.image("https://img.icons8.com/fluency/96/medical-doctor.png", width=80)
    st.title("PDI Control Center")
    st.info("Tier 1 Active: Gemini 3.1 Pro")
    st.markdown("---")
    
    uploaded_file = st.file_uploader("Upload Technical PDF", type="pdf")
    
    if st.button("Clear App Data"):
        st.session_state.gemini_file = None
        st.session_state.report_df = None
        st.session_state.chat_history = []
        st.rerun()

# --- File Processing ---
if uploaded_file:
    if st.session_state.current_filename != uploaded_file.name:
        st.session_state.gemini_file = None
        st.session_state.current_filename = uploaded_file.name
        st.session_state.report_df = None

    if st.session_state.gemini_file is None:
        with st.spinner("Processing PDF for Field Use..."):
            with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as temp_file:
                temp_file.write(uploaded_file.getbuffer())
                temp_path = temp_file.name
            
            gem_file = genai.upload_file(temp_path)
            while gem_file.state.name == "PROCESSING":
                time.sleep(2)
                gem_file = genai.get_file(gem_file.name)
            
            st.session_state.gemini_file = gem_file
            os.remove(temp_path)
            st.sidebar.success("✅ Analysis Ready!")

# --- MAIN DASHBOARD ---
st.title("📑 Smart Inspection Dashboard")

if st.session_state.gemini_file:
    tab1, tab2 = st.tabs(["📊 Technical Analysis", "💬 Field Q&A"])

    with tab1:
        st.subheader("Master PDI Specification Table")
        if st.button("Generate Full Analysis Report 🚀"):
            model = genai.GenerativeModel("gemini-3.1-pro-preview")
            
            with st.spinner("Extracting Specs into Detailed Hinglish Guide..."):
                prompt = (
                    "You are an Expert Senior Biomedical Engineer guiding a junior for a physical PDI. "
                    "Analyze this document and extract all technical specifications. "
                    "Provide the output ONLY as raw CSV text with exactly 4 columns: "
                    "1. S.No. "
                    "2. English (Spec) "
                    "3. Hindi Meaning (Write in easy Roman English/Hinglish) "
                    "4. Practical Inspection Guide (Explain EXACTLY how to check this on the physical machine. "
                    "Where is the part located? What does it look like? How to test it? "
                    "CRITICAL INSTRUCTION: You MUST write this ENTIRE 4th column in EASY HINGLISH (Roman Hindi) ONLY. "
                    "Do not use English sentences here. Example: 'Machine ke samne khade ho, top window ko haath se khol kar check karo ki wo smooth khul rahi hai ya nahi...'). "
                    "Do not use markdown blocks like ```csv. Just provide the raw text."
                )
                response = model.generate_content([st.session_state.gemini_file, prompt])
                
                try:
                    # AI output ko clean karna
                    csv_raw = response.text.replace('```csv', '').replace('```', '').strip()
                    st.session_state.report_df = pd.read_csv(io.StringIO(csv_raw))
                except Exception as e:
                    st.error("Table banane mein thoda error aaya. Ek baar fir se click karein.")

        if st.session_state.report_df is not None:
            # Screen par Table Dikhana
            st.dataframe(st.session_state.report_df, use_container_width=True)
            
            # --- PDF DOWNLOAD BUTTON ---
            st.markdown("### 📥 Save Report")
            try:
                pdf_data = create_pdf_table(st.session_state.report_df)
                st.download_button(
                    label="📄 Download Final PDF Report",
                    data=pdf_data,
                    file_name=f"PDI_Report_{st.session_state.current_filename}.pdf",
                    mime="application/pdf"
                )
            except Exception as e:
                st.error(f"PDF Banane mein error: {e}")

    with tab2:
        st.subheader("💬 Smart Q&A Assistant")
        for msg in st.session_state.chat_history:
            with st.chat_message(msg["role"]):
                st.markdown(msg["content"])
        
        query = st.chat_input("Ask anything about the document...")
        if query:
            st.session_state.chat_history.append({"role": "user", "content": query})
            with st.chat_message("user"):
                st.markdown(query)
            
            with st.chat_message("assistant"):
                with st.spinner("Searching..."):
                    model = genai.GenerativeModel("gemini-3-flash-preview")
                    response = model.generate_content([st.session_state.gemini_file, f"Answer in simple Hinglish: {query}"])
                    st.markdown(response.text)
                    st.session_state.chat_history.append({"role": "assistant", "content": response.text})
else:
    st.info("⬅️ PDI Manual ya Technical Specification PDF upload karke shuru karein.")
