import streamlit as st
import google.generativeai as genai
import tempfile
import os
import time
from fpdf import FPDF

# --- PDF Generation Function (Fixed for Bytes Error) ---
def create_pdf(text):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", size=12)
    
    # Title Header
    pdf.set_font("Helvetica", 'B', 16)
    pdf.cell(0, 10, txt="HITES PDI Technical Report", ln=True, align='C')
    pdf.set_font("Helvetica", size=10)
    pdf.cell(0, 10, txt="Generated by: Mohammad Sajid (Biomedical Engineer)", ln=True, align='C')
    pdf.ln(10)
    
    # Cleaning text for PDF compatibility
    # Unicode characters (Hindi/Symbols) ko ASCII mein convert kar rahe hain taaki error na aaye
    clean_text = text.encode('latin-1', 'ignore').decode('latin-1')
    clean_text = clean_text.replace('|', '  ')
    
    pdf.set_font("Helvetica", size=10)
    pdf.multi_cell(0, 8, txt=clean_text)
    
    # FIX: Output ko bytes mein convert karna zaruri hai
    return bytes(pdf.output())

# --- SECURE API CONFIGURATION ---
try:
    api_key = st.secrets["GEMINI_API_KEY"]
    genai.configure(api_key=api_key)
except Exception:
    st.error("❌ API Key nahi mili! Settings > Secrets check karein.")
    st.stop()

# --- Session State ---
if "gemini_file" not in st.session_state: st.session_state.gemini_file = None
if "current_filename" not in st.session_state: st.session_state.current_filename = ""
if "report_text" not in st.session_state: st.session_state.report_text = ""

# Professional Sidebar
with st.sidebar:
    st.title("🔬 PDI Control")
    uploaded_file = st.file_uploader("Upload Technical PDF", type="pdf")
    if st.button("Clear App Data"):
        st.session_state.gemini_file = None
        st.session_state.report_text = ""
        st.rerun()

# Processing Logic (Tier 1 Paid Access)
if uploaded_file:
    if st.session_state.current_filename != uploaded_file.name:
        st.session_state.gemini_file = None
        st.session_state.current_filename = uploaded_file.name

    if st.session_state.gemini_file is None:
        with st.spinner("Analyzing PDF for Field Use..."):
            with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as temp_file:
                temp_file.write(uploaded_file.getbuffer())
                temp_path = temp_file.name
            
            gem_file = genai.upload_file(temp_path)
            while gem_file.state.name == "PROCESSING":
                time.sleep(2)
                gem_file = genai.get_file(gem_file.name)
            st.session_state.gemini_file = gem_file
            os.remove(temp_path)
            st.sidebar.success("✅ Analysis Ready!")

# Main Dashboard
st.title("📑 Smart Inspection Dashboard")

if st.session_state.gemini_file:
    tab1, tab2 = st.tabs(["📊 Technical Analysis", "💬 Field Q&A"])

    with tab1:
        if st.button("Generate PDI Report 🚀"):
            # Using Gemini 3.1 Pro Preview as per latest updates
            model = genai.GenerativeModel("gemini-3.1-pro-preview")
            with st.spinner("Creating Master Table..."):
                prompt = (
                    "You are a Senior Biomedical Engineer. Analyze this document and create a table: "
                    "1. S.No. 2. English (Spec) 3. Hindi Meaning 4. Inspection Check. "
                    "Output ONLY the table. Use simple English for Hindi meanings to avoid PDF font errors."
                )
                response = model.generate_content([st.session_state.gemini_file, prompt])
                st.session_state.report_text = response.text
        
        if st.session_state.report_text:
            st.markdown(st.session_state.report_text)
            
            # --- FIXED PDF DOWNLOAD BUTTON ---
            try:
                pdf_bytes = create_pdf(st.session_state.report_text)
                st.download_button(
                    label="📥 Download Report as PDF",
                    data=pdf_bytes,
                    file_name=f"PDI_Report_{st.session_state.current_filename}.pdf",
                    mime="application/pdf"
                )
            except Exception as e:
                st.error(f"PDF System Error: {e}")

    with tab2:
        query = st.chat_input("Machine specifications ke bare mein puchein...")
        if query:
            # Using Flash for fast Q&A response
            model = genai.GenerativeModel("gemini-3-flash-preview")
            response = model.generate_content([st.session_state.gemini_file, f"Answer in Hindi: {query}"])
            st.write(response.text)
