import streamlit as st
import google.generativeai as genai
import tempfile
import os
import time
from fpdf import FPDF # fpdf2 library se

# --- PDF Generation Function (Fixed for Encoding) ---
def create_pdf(text):
    pdf = FPDF()
    pdf.add_page()
    # Hum 'Arial' ki jagah standard font use karenge aur characters clean karenge
    pdf.set_font("Helvetica", size=12)
    
    # Header
    pdf.set_font("Helvetica", 'B', 16)
    pdf.cell(0, 10, txt="HITES PDI Technical Report", ln=True, align='C')
    pdf.set_font("Helvetica", size=10)
    pdf.cell(0, 10, txt="Generated by: Mohammad Sajid (Biomedical Engineer)", ln=True, align='C')
    pdf.ln(10)
    
    # Content Cleaning: Special characters ko remove karna taaki error na aaye
    # \u25cf jaise symbols ko clean kar rahe hain
    clean_text = text.encode('ascii', 'ignore').decode('ascii')
    clean_text = clean_text.replace('|', '  ')
    
    pdf.set_font("Helvetica", size=10)
    pdf.multi_cell(0, 8, txt=clean_text)
    
    return pdf.output()

# --- SECURE API CONFIGURATION ---
try:
    api_key = st.secrets["GEMINI_API_KEY"]
    genai.configure(api_key=api_key)
except Exception:
    st.error("❌ API Key nahi mili! Settings > Secrets check karein.")
    st.stop()

# --- Session State ---
if "gemini_file" not in st.session_state: st.session_state.gemini_file = None
if "current_filename" not in st.session_state: st.session_state.current_filename = ""
if "report_text" not in st.session_state: st.session_state.report_text = ""

# Sidebar
with st.sidebar:
    st.title("🔬 PDI Control")
    uploaded_file = st.file_uploader("Upload Technical PDF", type="pdf")
    if st.button("Clear App Data"):
        st.session_state.gemini_file = None
        st.session_state.report_text = ""
        st.rerun()

if uploaded_file:
    if st.session_state.current_filename != uploaded_file.name:
        st.session_state.gemini_file = None
        st.session_state.current_filename = uploaded_file.name

    if st.session_state.gemini_file is None:
        with st.spinner("Processing PDF..."):
            with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as temp_file:
                temp_file.write(uploaded_file.getbuffer())
                temp_path = temp_file.name
            
            # Tier 1 Paid model use ho raha hai
            gem_file = genai.upload_file(temp_path)
            while gem_file.state.name == "PROCESSING":
                time.sleep(2)
                gem_file = genai.get_file(gem_file.name)
            st.session_state.gemini_file = gem_file
            os.remove(temp_path)

# Main Dashboard
st.title("📑 Smart Inspection Dashboard")

if st.session_state.gemini_file:
    tab1, tab2 = st.tabs(["📊 Technical Analysis", "💬 Field Q&A"])

    with tab1:
        if st.button("Generate PDI Report 🚀"):
            # Latest Gemini 3.1 Pro Preview
            model = genai.GenerativeModel("gemini-3.1-pro-preview")
            with st.spinner("Analyzing specifications..."):
                prompt = (
                    "Analyze this document as a Biomedical Engineer. Create a detailed table: "
                    "1. S.No. 2. English (Spec) 3. Hindi Meaning 4. Inspection Check. "
                    "Output ONLY the table without markdown characters like bold or bullets inside cells."
                )
                response = model.generate_content([st.session_state.gemini_file, prompt])
                st.session_state.report_text = response.text
        
        if st.session_state.report_text:
            st.markdown(st.session_state.report_text)
            
            # --- FIXED PDF DOWNLOAD ---
            try:
                pdf_bytes = create_pdf(st.session_state.report_text)
                st.download_button(
                    label="📥 Download Report as PDF",
                    data=pdf_bytes,
                    file_name=f"PDI_Report_{st.session_state.current_filename}.pdf",
                    mime="application/pdf"
                )
            except Exception as e:
                st.error(f"PDF Generation Error: {e}")

    with tab2:
        query = st.chat_input("Ask a question about the document...")
        if query:
            model = genai.GenerativeModel("gemini-3-flash-preview")
            response = model.generate_content([st.session_state.gemini_file, f"Answer in Hindi: {query}"])
            st.write(response.text)
